# Generated by Django 5.0.6 on 2024-05-22 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_reviews'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviews',
            options={'verbose_name': 'Review', 'verbose_name_plural': 'Reviews'},
        ),
    ]
