# Generated by Django 5.0.6 on 2024-05-23 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_books_cover'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='books',
            options={'permissions': [('special_status', 'Can read all books')], 'verbose_name': 'Book', 'verbose_name_plural': 'Books'},
        ),
    ]
